/*
	newChannel(uint deposit, bytes32 id)
	closeChannel(address player, bytes32 id, uint value, bool add)
	getOpenChannel(address player, bytes32 (bool)
 */


module.exports = {
	factory:{
		address: '0x16f3751278a07c96fd969a816504c51e0857856c',
		abi:     [{'constant':true,'inputs':[],'name':'meta_name','outputs':[{'name':'','type':'string'}],'payable':false,'type':'function'},{'constant':true,'inputs':[],'name':'meta_link','outputs':[{'name':'','type':'string'}],'payable':false,'type':'function'},{'constant':true,'inputs':[],'name':'developer','outputs':[{'name':'','type':'address'}],'payable':false,'type':'function'},{'constant':false,'inputs':[],'name':'createGameChannel','outputs':[{'name':'Address','type':'address'}],'payable':false,'type':'function'},{'constant':true,'inputs':[],'name':'meta_version','outputs':[{'name':'','type':'uint256'}],'payable':false,'type':'function'},{'constant':true,'inputs':[],'name':'meta_code','outputs':[{'name':'','type':'string'}],'payable':false,'type':'function'},{'constant':true,'inputs':[{'name':'','type':'address'}],'name':'validGames','outputs':[{'name':'','type':'bool'}],'payable':false,'type':'function'},{'inputs':[{'name':'dev','type':'address'},{'name':'version','type':'uint256'},{'name':'code','type':'string'},{'name':'name','type':'string'},{'name':'link','type':'string'}],'payable':false,'type':'constructor'},{'anonymous':false,'inputs':[{'indexed':false,'name':'','type':'address'}],'name':'Channel','type':'event'}]
	},

	abi:[{'constant':false,'inputs':[{'name':'money','type':'uint256'}],'name':'refund','outputs':[],'payable':false,'type':'function'},{'constant':false,'inputs':[{'name':'player','type':'address'},{'name':'id','type':'bytes32'},{'name':'value','type':'uint256'},{'name':'add','type':'bool'}],'name':'closeChannel','outputs':[],'payable':false,'type':'function'},{'constant':true,'inputs':[],'name':'meta_name','outputs':[{'name':'','type':'string'}],'payable':false,'type':'function'},{'constant':true,'inputs':[],'name':'gameDeveloper','outputs':[{'name':'','type':'address'}],'payable':false,'type':'function'},{'constant':false,'inputs':[{'name':'deposit','type':'uint256'},{'name':'id','type':'bytes32'}],'name':'newChannel','outputs':[],'payable':false,'type':'function'},{'constant':true,'inputs':[],'name':'meta_factory','outputs':[{'name':'','type':'address'}],'payable':false,'type':'function'},{'constant':true,'inputs':[],'name':'BankrollDeposit','outputs':[{'name':'','type':'uint256'}],'payable':false,'type':'function'},{'constant':true,'inputs':[],'name':'owner','outputs':[{'name':'','type':'address'}],'payable':false,'type':'function'},{'constant':true,'inputs':[{'name':'player','type':'address'},{'name':'id','type':'bytes32'}],'name':'getOpenChannel','outputs':[{'name':'','type':'bool'}],'payable':false,'type':'function'},{'constant':true,'inputs':[],'name':'tokenAddress','outputs':[{'name':'','type':'address'}],'payable':false,'type':'function'},{'constant':true,'inputs':[],'name':'meta_link','outputs':[{'name':'','type':'string'}],'payable':false,'type':'function'},{'constant':true,'inputs':[{'name':'','type':'address'},{'name':'','type':'bytes32'}],'name':'allChannels','outputs':[{'name':'player','type':'address'},{'name':'balance','type':'uint256'},{'name':'open','type':'bool'}],'payable':false,'type':'function'},{'constant':true,'inputs':[],'name':'refAddress','outputs':[{'name':'','type':'address'}],'payable':false,'type':'function'},{'constant':true,'inputs':[],'name':'meta_version','outputs':[{'name':'','type':'uint256'}],'payable':false,'type':'function'},{'constant':false,'inputs':[{'name':'newOwner','type':'address'}],'name':'transferOwnership','outputs':[],'payable':false,'type':'function'},{'constant':true,'inputs':[],'name':'meta_code','outputs':[{'name':'','type':'string'}],'payable':false,'type':'function'},{'inputs':[{'name':'newOwner','type':'address'},{'name':'dev','type':'address'},{'name':'version','type':'uint256'},{'name':'code','type':'string'},{'name':'name','type':'string'},{'name':'link','type':'string'},{'name':'factory','type':'address'}],'payable':false,'type':'constructor'}]
}
